// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUHU2VZx3Kdg1d9g9fkG3tdJMQSFBq0hA',
    appId: '1:788002160614:web:9a82f89ef3ada95ce0a027',
    messagingSenderId: '788002160614',
    projectId: 'veloxorder-f95e2',
    authDomain: 'veloxorder-f95e2.firebaseapp.com',
    storageBucket: 'veloxorder-f95e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8E91xkfR1hk2pc9po-D0DE1V-m1Znt1o',
    appId: '1:788002160614:android:7076765e1a291c7de0a027',
    messagingSenderId: '788002160614',
    projectId: 'veloxorder-f95e2',
    storageBucket: 'veloxorder-f95e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8mDPqdbuzSV549oT_NUUpD8DYREhVesQ',
    appId: '1:788002160614:ios:8d4a1e671be6583ce0a027',
    messagingSenderId: '788002160614',
    projectId: 'veloxorder-f95e2',
    storageBucket: 'veloxorder-f95e2.firebasestorage.app',
    iosBundleId: 'com.ma2mori.veloxorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8mDPqdbuzSV549oT_NUUpD8DYREhVesQ',
    appId: '1:788002160614:ios:8d4a1e671be6583ce0a027',
    messagingSenderId: '788002160614',
    projectId: 'veloxorder-f95e2',
    storageBucket: 'veloxorder-f95e2.firebasestorage.app',
    iosBundleId: 'com.ma2mori.veloxorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUHU2VZx3Kdg1d9g9fkG3tdJMQSFBq0hA',
    appId: '1:788002160614:web:8acb8df554a130d3e0a027',
    messagingSenderId: '788002160614',
    projectId: 'veloxorder-f95e2',
    authDomain: 'veloxorder-f95e2.firebaseapp.com',
    storageBucket: 'veloxorder-f95e2.firebasestorage.app',
  );
}
